function WP = importWP(filename, dataLines)
%IMPORTFILE Import data from a text file
%  WP1 = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the numeric data.
%
%  WP1 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  WP1 = importfile("C:\Users\pgogende\Downloads\WP1.waypoints", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Feb-2022 12:13:46

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "VarName9", "VarName10", "Var11", "Var12"];
opts.SelectedVariableNames = ["VarName9", "VarName10"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "double", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var11", "Var12"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var11", "Var12"], "EmptyFieldRule", "auto");

% Import the data
WP1 = readtable(filename, opts);

%% Convert to output type
WP = table2array(WP1);
end